;;; ------------------------------------------------------------ constants

;;; event kinds reported by the shim (see c/asyncio.c)
(define AIO-EV-ACCEPT 1)
(define AIO-EV-READ 2)
(define AIO-EV-WRITE 3)
(define AIO-EV-CONNECT 4)
(define AIO-EV-SHUTDOWN 5)
(define AIO-EV-FS 6)
(define AIO-EV-DNS 7)
(define AIO-EV-CLOSE 8)
(define AIO-EV-UDP-RECV 9)
(define AIO-EV-UDP-SEND 10)
(define AIO-EV-NAMEINFO 11)
(define AIO-EV-RANDOM 12)
(define AIO-EV-POLL 13)
(define AIO-EV-PROCESS 14)
(define AIO-EV-SIGNAL 15)
(define AIO-EV-FS-EVENT 16)
(define AIO-EV-FS-POLL 17)

;;; per-poll dispatch bound so a sustained completion stream cannot starve
;;; runnable tasks
(define aio-dispatch-bound 256)

;;; ------------------------------------------------------------ conditions

(define-condition-type &async-io &error
  make-async-io-condition% %async-io-condition?
  (operation %async-io-condition-operation)
  (handle %async-io-condition-handle)
  (path %async-io-condition-path)
  (code %async-io-condition-code))

;;; ------------------------------------------------------- shim loading

(define aio-loaded? (box #f))
(define aio-load-mutex (make-mutex))

(define aio-loaded?/acquire
  (lambda ()
    (let loop ()
      (let ([loaded? (unbox aio-loaded?)])
        (if (box-cas! aio-loaded? loaded? loaded?)
            loaded?
            (loop))))))

(define aio-loaded?/release!
  (lambda ()
    (let loop ()
      (let ([loaded? (aio-loaded?/acquire)])
        (unless (or loaded? (box-cas! aio-loaded? #f #t))
          (loop))))))

;;; foreign-procedure bindings, resolved lazily from the statically linked
;;; kernel
(define aio-loop-open #f)
(define aio-set-notify #f)
(define aio-loop-run #f)
(define aio-loop-alive #f)
(define aio-loop-destroy #f)
(define aio-wakeup-init #f)
(define aio-wakeup-send #f)
(define aio-bridge-init #f)
(define aio-bridge-start #f)
(define aio-bridge-stop #f)
(define aio-handle-close #f)
(define aio-handle-is-closing #f)
(define aio-tcp-init #f)
(define aio-tcp-bind #f)
(define aio-listen-start #f)
(define aio-accept #f)
(define aio-tcp-connect #f)
(define aio-pipe-init #f)
(define aio-pipe-bind #f)
(define aio-pipe-connect #f)
(define aio-read-start #f)
(define aio-read-stop #f)
(define aio-read-copy #f)
(define aio-free #f)
(define aio-write #f)
(define aio-shutdown #f)
(define aio-udp-init #f)
(define aio-udp-bind #f)
(define aio-udp-connect #f)
(define aio-udp-recv-start #f)
(define aio-udp-recv-stop #f)
(define aio-udp-recv-copy #f)
(define aio-udp-recv-addr #f)
(define aio-udp-recv-free #f)
(define aio-udp-send #f)
(define aio-udp-address #f)
(define aio-udp-set-membership #f)
(define aio-udp-set-option #f)
(define aio-udp-set-multicast-interface #f)
(define aio-dns-lookup #f)
(define aio-dns-cancel #f)
(define aio-dns-count #f)
(define aio-dns-addr #f)
(define aio-dns-free #f)
(define aio-dns-reverse #f)
(define aio-dns-reverse-cancel #f)
(define aio-dns-reverse-copy #f)
(define aio-dns-reverse-free #f)
(define aio-random #f)
(define aio-random-cancel #f)
(define aio-random-copy #f)
(define aio-random-free #f)
(define aio-poll-init #f)
(define aio-poll-start #f)
(define aio-poll-stop #f)
(define aio-process-spawn #f)
(define aio-process-pid #f)
(define aio-process-kill #f)
(define aio-kill #f)
(define aio-process-term-signal #f)
(define aio-process-result-free #f)
(define aio-signal-init #f)
(define aio-signal-start #f)
(define aio-signal-stop #f)
(define aio-fs-event-init #f)
(define aio-fs-event-start #f)
(define aio-fs-event-stop #f)
(define aio-fs-event-result-copy #f)
(define aio-fs-event-result-free #f)
(define aio-fs-poll-init #f)
(define aio-fs-poll-start #f)
(define aio-fs-poll-stop #f)
(define aio-fs-poll-result-field #f)
(define aio-fs-poll-result-free #f)
(define aio-tty-init #f)
(define aio-tty-set-mode #f)
(define aio-tty-winsize #f)
(define aio-tty-get-vterm-state #f)
(define aio-tty-set-vterm-state #f)
(define aio-tty-reset-mode #f)
(define aio-system-u64 #f)
(define aio-system-double #f)
(define aio-system-string #f)
(define aio-uname-string #f)
(define aio-cpu-info #f)
(define aio-cpu-info-count #f)
(define aio-cpu-info-model #f)
(define aio-cpu-info-field #f)
(define aio-cpu-info-free #f)
(define aio-interface-info #f)
(define aio-interface-count #f)
(define aio-interface-name #f)
(define aio-interface-address #f)
(define aio-interface-internal #f)
(define aio-interface-physical #f)
(define aio-interface-free #f)
(define aio-rusage #f)
(define aio-rusage-field #f)
(define aio-rusage-free #f)
(define aio-loop-metric #f)
(define aio-fs-open #f)
(define aio-fs-read #f)
(define aio-fs-write #f)
(define aio-fs-close-fd #f)
(define aio-fs-close-now #f)
(define aio-fs-stat #f)
(define aio-fs-fstat #f)
(define aio-fs-unlink #f)
(define aio-fs-rename #f)
(define aio-fs-mkdir #f)
(define aio-fs-rmdir #f)
(define aio-fs-copyfile #f)
(define aio-fs-mkdtemp #f)
(define aio-fs-mkstemp #f)
(define aio-fs-scandir #f)
(define aio-fs-scandir-next #f)
(define aio-fs-opendir #f)
(define aio-fs-readdir #f)
(define aio-fs-closedir #f)
(define aio-fs-closedir-now #f)
(define aio-fs-result-ptr #f)
(define aio-fs-readdir-entry #f)
(define aio-fs-fsync #f)
(define aio-fs-fdatasync #f)
(define aio-fs-ftruncate #f)
(define aio-fs-sendfile #f)
(define aio-fs-access #f)
(define aio-fs-chmod #f)
(define aio-fs-fchmod #f)
(define aio-fs-utime #f)
(define aio-fs-futime #f)
(define aio-fs-lstat #f)
(define aio-fs-link #f)
(define aio-fs-readlink #f)
(define aio-fs-result-string-length #f)
(define aio-fs-result-string-copy #f)
(define aio-fs-result-path-length #f)
(define aio-fs-result-path-copy #f)
(define aio-fs-chown #f)
(define aio-fs-statfs #f)
(define aio-fs-statfs-field #f)
(define aio-fs-req-free #f)
(define aio-fs-cancel #f)
(define aio-fs-data #f)
(define aio-fs-buf-free #f)
(define aio-fs-stat-field #f)
(define aio-strerror-into #f)
(define aio-err-name-into #f)
(define aio-eof-code #f)
(define aio-eagain-code #f)

(define aio-resolve!
  (lambda ()
    (set! aio-loop-open (foreign-procedure "aio_loop_open" () void*))
    (set! aio-set-notify (foreign-procedure "aio_set_notify" (void* void*) void))
    (set! aio-loop-run (foreign-procedure "aio_loop_run" (void* int) int))
    (set! aio-loop-alive (foreign-procedure "aio_loop_alive" (void*) int))
    (set! aio-loop-destroy (foreign-procedure "aio_loop_destroy" (void*) int))
    (set! aio-wakeup-init (foreign-procedure "aio_wakeup_init" (void*) void*))
    (set! aio-wakeup-send (foreign-procedure "aio_wakeup_send" (void*) int))
    (set! aio-bridge-init (foreign-procedure "aio_bridge_init" (void*) void*))
    (set! aio-bridge-start (foreign-procedure "aio_bridge_start" (void* integer-64) int))
    (set! aio-bridge-stop (foreign-procedure "aio_bridge_stop" (void*) int))
    (set! aio-handle-close (foreign-procedure "aio_handle_close" (void*) void))
    (set! aio-handle-is-closing (foreign-procedure "aio_handle_is_closing" (void*) int))
    (set! aio-tcp-init (foreign-procedure "aio_tcp_init" (void* integer-64) void*))
    (set! aio-tcp-bind (foreign-procedure "aio_tcp_bind" (void* string integer-64) int))
    (set! aio-listen-start (foreign-procedure "aio_listen_start" (void* integer-64) int))
    (set! aio-accept (foreign-procedure "aio_accept" (void* void*) int))
    (set! aio-tcp-connect (foreign-procedure "aio_tcp_connect" (void* string integer-64 integer-64) int))
    (set! aio-pipe-init (foreign-procedure "aio_pipe_init" (void* integer-64) void*))
    (set! aio-pipe-bind (foreign-procedure "aio_pipe_bind" (void* string) int))
    (set! aio-pipe-connect (foreign-procedure "aio_pipe_connect" (void* string integer-64) int))
    (set! aio-read-start (foreign-procedure "aio_read_start" (void*) int))
    (set! aio-read-stop (foreign-procedure "aio_read_stop" (void*) int))
    (set! aio-read-copy (foreign-procedure "aio_read_copy" (void* u8* integer-64) void))
    (set! aio-free (foreign-procedure "aio_free" (void*) void))
    (set! aio-write (foreign-procedure "aio_write" (void* u8* integer-64 integer-64) int))
    (set! aio-shutdown (foreign-procedure "aio_shutdown" (void* integer-64) int))
    (set! aio-udp-init (foreign-procedure "aio_udp_init" (void* integer-64) void*))
    (set! aio-udp-bind (foreign-procedure "aio_udp_bind" (void* string integer-64 int) int))
    (set! aio-udp-connect (foreign-procedure "aio_udp_connect" (void* string integer-64) int))
    (set! aio-udp-recv-start (foreign-procedure "aio_udp_recv_start" (void*) int))
    (set! aio-udp-recv-stop (foreign-procedure "aio_udp_recv_stop" (void*) int))
    (set! aio-udp-recv-copy (foreign-procedure "aio_udp_recv_copy" (void* u8* integer-64) void))
    (set! aio-udp-recv-addr (foreign-procedure "aio_udp_recv_addr" (void* u8* integer-64) integer-64))
    (set! aio-udp-recv-free (foreign-procedure "aio_udp_recv_free" (void*) void))
    (set! aio-udp-send (foreign-procedure "aio_udp_send" (void* u8* integer-64 string integer-64 integer-64) int))
    (set! aio-udp-address (foreign-procedure "aio_udp_address" (void* int u8* integer-64) integer-64))
    (set! aio-udp-set-membership (foreign-procedure "aio_udp_set_membership" (void* string string string int) int))
    (set! aio-udp-set-option (foreign-procedure "aio_udp_set_option" (void* int integer-64) int))
    (set! aio-udp-set-multicast-interface (foreign-procedure "aio_udp_set_multicast_interface" (void* string) int))
    (set! aio-dns-lookup (foreign-procedure "aio_dns_lookup" (void* string string integer-64) integer-64))
    (set! aio-dns-cancel (foreign-procedure "aio_dns_cancel" (void*) int))
    (set! aio-dns-count (foreign-procedure "aio_dns_count" (void*) integer-64))
    (set! aio-dns-addr (foreign-procedure "aio_dns_addr" (void* integer-64 u8* integer-64) integer-64))
    (set! aio-dns-free (foreign-procedure "aio_dns_free" (void*) void))
    (set! aio-dns-reverse (foreign-procedure "aio_dns_reverse" (void* string integer-64 int integer-64) integer-64))
    (set! aio-dns-reverse-cancel (foreign-procedure "aio_dns_reverse_cancel" (void*) int))
    (set! aio-dns-reverse-copy (foreign-procedure "aio_dns_reverse_copy" (void* int u8* integer-64) integer-64))
    (set! aio-dns-reverse-free (foreign-procedure "aio_dns_reverse_free" (void*) void))
    (set! aio-random (foreign-procedure "aio_random" (void* integer-64 integer-64) integer-64))
    (set! aio-random-cancel (foreign-procedure "aio_random_cancel" (void*) int))
    (set! aio-random-copy (foreign-procedure "aio_random_copy" (void* u8*) void))
    (set! aio-random-free (foreign-procedure "aio_random_free" (void*) void))
    (set! aio-poll-init (foreign-procedure "aio_poll_init" (void* integer-64 integer-64) void*))
    (set! aio-poll-start (foreign-procedure "aio_poll_start" (void* int) int))
    (set! aio-poll-stop (foreign-procedure "aio_poll_stop" (void*) int))
    (set! aio-process-spawn
      (foreign-procedure "aio_process_spawn"
        (void* integer-64 string u8* integer-64 u8* integer-64 int string int
         int integer-64 void* int integer-64 void* int integer-64 void*)
        integer-64))
    (set! aio-process-pid (foreign-procedure "aio_process_pid" (void*) integer-64))
    (set! aio-process-kill (foreign-procedure "aio_process_kill" (void* int) int))
    (set! aio-kill (foreign-procedure "aio_kill" (integer-64 int) int))
    (set! aio-process-term-signal (foreign-procedure "aio_process_term_signal" (void*) integer-64))
    (set! aio-process-result-free (foreign-procedure "aio_process_result_free" (void*) void))
    (set! aio-signal-init (foreign-procedure "aio_signal_init" (void* integer-64) void*))
    (set! aio-signal-start (foreign-procedure "aio_signal_start" (void* int int) int))
    (set! aio-signal-stop (foreign-procedure "aio_signal_stop" (void*) int))
    (set! aio-fs-event-init (foreign-procedure "aio_fs_event_init" (void* integer-64) void*))
    (set! aio-fs-event-start (foreign-procedure "aio_fs_event_start" (void* string int) int))
    (set! aio-fs-event-stop (foreign-procedure "aio_fs_event_stop" (void*) int))
    (set! aio-fs-event-result-copy (foreign-procedure "aio_fs_event_result_copy" (void* u8* integer-64) int))
    (set! aio-fs-event-result-free (foreign-procedure "aio_fs_event_result_free" (void*) void))
    (set! aio-fs-poll-init (foreign-procedure "aio_fs_poll_init" (void* integer-64) void*))
    (set! aio-fs-poll-start (foreign-procedure "aio_fs_poll_start" (void* string integer-64) int))
    (set! aio-fs-poll-stop (foreign-procedure "aio_fs_poll_stop" (void*) int))
    (set! aio-fs-poll-result-field (foreign-procedure "aio_fs_poll_result_field" (void* int integer-64) integer-64))
    (set! aio-fs-poll-result-free (foreign-procedure "aio_fs_poll_result_free" (void*) void))
    (set! aio-tty-init (foreign-procedure "aio_tty_init" (void* integer-64 integer-64) void*))
    (set! aio-tty-set-mode (foreign-procedure "aio_tty_set_mode" (void* int) int))
    (set! aio-tty-winsize (foreign-procedure "aio_tty_winsize" (void* int) int))
    (set! aio-tty-get-vterm-state (foreign-procedure "aio_tty_get_vterm_state" () int))
    (set! aio-tty-set-vterm-state (foreign-procedure "aio_tty_set_vterm_state" (int) void))
    (set! aio-tty-reset-mode (foreign-procedure "aio_tty_reset_mode" () void))
    (set! aio-system-u64 (foreign-procedure "aio_system_u64" (int) unsigned-64))
    (set! aio-system-double (foreign-procedure "aio_system_double" (int) double))
    (set! aio-system-string (foreign-procedure "aio_system_string" (int u8* integer-64) int))
    (set! aio-uname-string (foreign-procedure "aio_uname_string" (int u8* integer-64) int))
    (set! aio-cpu-info (foreign-procedure "aio_cpu_info" () void*))
    (set! aio-cpu-info-count (foreign-procedure "aio_cpu_info_count" (void*) integer-64))
    (set! aio-cpu-info-model (foreign-procedure "aio_cpu_info_model" (void* integer-64 u8* integer-64) int))
    (set! aio-cpu-info-field (foreign-procedure "aio_cpu_info_field" (void* integer-64 int) unsigned-64))
    (set! aio-cpu-info-free (foreign-procedure "aio_cpu_info_free" (void*) void))
    (set! aio-interface-info (foreign-procedure "aio_interface_info" () void*))
    (set! aio-interface-count (foreign-procedure "aio_interface_count" (void*) integer-64))
    (set! aio-interface-name (foreign-procedure "aio_interface_name" (void* integer-64 u8* integer-64) int))
    (set! aio-interface-address (foreign-procedure "aio_interface_address" (void* integer-64 int u8* integer-64) integer-64))
    (set! aio-interface-internal (foreign-procedure "aio_interface_internal" (void* integer-64) int))
    (set! aio-interface-physical (foreign-procedure "aio_interface_physical" (void* integer-64 u8*) int))
    (set! aio-interface-free (foreign-procedure "aio_interface_free" (void*) void))
    (set! aio-rusage (foreign-procedure "aio_rusage" () void*))
    (set! aio-rusage-field (foreign-procedure "aio_rusage_field" (void* int) integer-64))
    (set! aio-rusage-free (foreign-procedure "aio_rusage_free" (void*) void))
    (set! aio-loop-metric (foreign-procedure "aio_loop_metric" (void* int) integer-64))
    (set! aio-fs-open (foreign-procedure "aio_fs_open" (void* string int integer-64 integer-64) integer-64))
    (set! aio-fs-read (foreign-procedure "aio_fs_read" (void* integer-64 integer-64 integer-64 integer-64) integer-64))
    (set! aio-fs-write (foreign-procedure "aio_fs_write" (void* integer-64 u8* integer-64 integer-64 integer-64) integer-64))
    (set! aio-fs-close-fd (foreign-procedure "aio_fs_close_fd" (void* integer-64 integer-64) integer-64))
    (set! aio-fs-close-now (foreign-procedure "aio_fs_close_now" (integer-64) int))
    (set! aio-fs-stat (foreign-procedure "aio_fs_stat" (void* string integer-64) integer-64))
    (set! aio-fs-fstat (foreign-procedure "aio_fs_fstat" (void* integer-64 integer-64) integer-64))
    (set! aio-fs-unlink (foreign-procedure "aio_fs_unlink" (void* string integer-64) integer-64))
    (set! aio-fs-rename (foreign-procedure "aio_fs_rename" (void* string string integer-64) integer-64))
    (set! aio-fs-mkdir (foreign-procedure "aio_fs_mkdir" (void* string integer-64 integer-64) integer-64))
    (set! aio-fs-rmdir (foreign-procedure "aio_fs_rmdir" (void* string integer-64) integer-64))
    (set! aio-fs-copyfile (foreign-procedure "aio_fs_copyfile" (void* string string int integer-64) integer-64))
    (set! aio-fs-mkdtemp (foreign-procedure "aio_fs_mkdtemp" (void* string integer-64) integer-64))
    (set! aio-fs-mkstemp (foreign-procedure "aio_fs_mkstemp" (void* string integer-64) integer-64))
    (set! aio-fs-scandir (foreign-procedure "aio_fs_scandir" (void* string integer-64) integer-64))
    (set! aio-fs-scandir-next (foreign-procedure "aio_fs_scandir_next" (void* u8* integer-64) int))
    (set! aio-fs-opendir (foreign-procedure "aio_fs_opendir" (void* string integer-64) integer-64))
    (set! aio-fs-readdir (foreign-procedure "aio_fs_readdir" (void* void* integer-64 integer-64) integer-64))
    (set! aio-fs-closedir (foreign-procedure "aio_fs_closedir" (void* void* integer-64) integer-64))
    (set! aio-fs-closedir-now (foreign-procedure "aio_fs_closedir_now" (void*) int))
    (set! aio-fs-result-ptr (foreign-procedure "aio_fs_result_ptr" (void*) void*))
    (set! aio-fs-readdir-entry (foreign-procedure "aio_fs_readdir_entry" (void* integer-64 u8* integer-64) int))
    (set! aio-fs-fsync (foreign-procedure "aio_fs_fsync" (void* integer-64 integer-64) integer-64))
    (set! aio-fs-fdatasync (foreign-procedure "aio_fs_fdatasync" (void* integer-64 integer-64) integer-64))
    (set! aio-fs-ftruncate (foreign-procedure "aio_fs_ftruncate" (void* integer-64 integer-64 integer-64) integer-64))
    (set! aio-fs-sendfile (foreign-procedure "aio_fs_sendfile" (void* integer-64 integer-64 integer-64 integer-64 integer-64) integer-64))
    (set! aio-fs-access (foreign-procedure "aio_fs_access" (void* string int integer-64) integer-64))
    (set! aio-fs-chmod (foreign-procedure "aio_fs_chmod" (void* string integer-64 integer-64) integer-64))
    (set! aio-fs-fchmod (foreign-procedure "aio_fs_fchmod" (void* integer-64 integer-64 integer-64) integer-64))
    (set! aio-fs-utime (foreign-procedure "aio_fs_utime" (void* string double double int integer-64) integer-64))
    (set! aio-fs-futime (foreign-procedure "aio_fs_futime" (void* integer-64 double double integer-64) integer-64))
    (set! aio-fs-lstat (foreign-procedure "aio_fs_lstat" (void* string integer-64) integer-64))
    (set! aio-fs-link (foreign-procedure "aio_fs_link" (void* string string int int integer-64) integer-64))
    (set! aio-fs-readlink (foreign-procedure "aio_fs_readlink" (void* string int integer-64) integer-64))
    (set! aio-fs-result-string-length (foreign-procedure "aio_fs_result_string_length" (void*) integer-64))
    (set! aio-fs-result-string-copy (foreign-procedure "aio_fs_result_string_copy" (void* u8* integer-64) int))
    (set! aio-fs-result-path-length (foreign-procedure "aio_fs_result_path_length" (void*) integer-64))
    (set! aio-fs-result-path-copy (foreign-procedure "aio_fs_result_path_copy" (void* u8* integer-64) int))
    (set! aio-fs-chown (foreign-procedure "aio_fs_chown" (void* string integer-64 integer-64 integer-64 int integer-64) integer-64))
    (set! aio-fs-statfs (foreign-procedure "aio_fs_statfs" (void* string integer-64) integer-64))
    (set! aio-fs-statfs-field (foreign-procedure "aio_fs_statfs_field" (void* int) unsigned-64))
    (set! aio-fs-req-free (foreign-procedure "aio_fs_req_free" (void*) void))
    (set! aio-fs-cancel (foreign-procedure "aio_fs_cancel" (void*) int))
    (set! aio-fs-data (foreign-procedure "aio_fs_data" (void*) void*))
    (set! aio-fs-buf-free (foreign-procedure "aio_fs_buf_free" (void*) void))
    (set! aio-fs-stat-field (foreign-procedure "aio_fs_stat_field" (void* integer-64) integer-64))
    (set! aio-strerror-into (foreign-procedure "aio_strerror_into" (integer-64 u8* integer-64) void))
    (set! aio-err-name-into (foreign-procedure "aio_err_name_into" (integer-64 u8* integer-64) void))
    (set! aio-eof-code (foreign-procedure "aio_eof_code" () integer-64))
    (set! aio-eagain-code (foreign-procedure "aio_eagain_code" () integer-64))))

(define aio-resolve-kernel!
  (lambda ()
    (unless (aio-loaded?/acquire)
      (with-mutex aio-load-mutex
        (unless (aio-loaded?/acquire)
          ;; Publish the initialized procedure slots only after every foreign
          ;; entry point has been resolved.
          (aio-resolve!)
          (aio-loaded?/release!))))))
